---
title: "EMLO SPARQL Tests"
output: pdf_document
---

# SPARQL Tutorial


```{r}
# install.packages("SPARQL")
library(SPARQL) # SPARQL querying package
library(ggplot2)
```

This is from the SPARQL documentation

```{r}
d <- SPARQL(url="http://services.data.gov.uk/reference/sparql",
            query="SELECT * WHERE { ?s ?p ?o . } LIMIT 10",
            ns=c('time','<http://www.w3.org/2006/time#>'))
is.data.frame(d$results)
```

The code here is taken from the following tutorial on [r-bloggers.com](http://www.r-bloggers.com/sparql-with-r-in-less-than-5-minutes/).

Get packages


First query:

```{r}
# Step 1 - Set up preliminaries and define query
# Define the data.gov endpoint
endpoint <- "http://services.data.gov/sparql"
# create query statement
query <-
"PREFIX  dgp1187: <http://data-gov.tw.rpi.edu/vocab/p/1187/>
SELECT ?ye ?fi ?ac
WHERE {
?s dgp1187:year ?ye .
?s dgp1187:fires ?fi .
?s dgp1187:acres ?ac .
}"
 
# Step 2 - Use SPARQL package to submit query and save results to a data frame
qd <- SPARQL(endpoint,query)
df <- qd$results
```

Couldn't get above to work so switching to another guide:

```{r}
endpoint <- "http://services.data.gov.uk/education/sparql"

query <- "prefix sch-ont: <http://education.data.gov.uk/ontology/school#>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT ?name WHERE {
?school a sch-ont:School; sch-ont:establishmentName ?name;
sch-ont:districtAdministrative
<http://education.data.gov.uk/placeholder-id/administrativeDistrict/Bath-... ;
sch-ont:nurseryProvision "true"^^xsd:boolean
}
ORDER BY ?name"

qd <- SPARQL(endpoint,query)
df <- qd$results


```


# EMLO Attempt

```{r}
emlo.endpoint <- "http://ldf.fi/emlo-open/sparql"

emlo.type.query <- "SELECT ?item ?label ?aType ?aTypeLabel (COUNT(*) AS ?references) WHERE {
  ?item rdf:type ?type .
  ?item rdf:type ?aType .
  OPTIONAL {
    ?item rdfs:label|skos:prefLabel ?label
  }
  OPTIONAL {
    ?aType rdfs:label|skos:prefLabel ?aTypeLabel"

```

