---
title: "Irish Surgeons"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)
```

## Irish Surgeons

This map contains the birth locations of several hundred Irish-born surgeons who later moved to India.

The interactivity provided is as follows:

- Pan and zoom with the cursor/trackpad
- Zoom with the + / - button
- Click points to get information on the number of births at the location

```{r data_processing}
place_of_birth <-
  read.csv(file = "data/Place of Birth_MartinHadley.csv", stringsAsFactors = FALSE)

## =========================== Drop Missing and Split Locations =================
## ==============================================================================
library(stringr)

place_of_birth <- place_of_birth[!is.na(place_of_birth$Lat.Long), ]
place_of_birth$Lat.Long <- trimws(place_of_birth$Lat.Long)
## Kill commas
place_of_birth$Lat.Long <-
  str_replace(place_of_birth$Lat.Long,
              pattern = ",",
              replacement = "")

lat_long_splittings <- strsplit(place_of_birth$Lat.Long, "\\s+")
place_of_birth$Lat <- sapply(lat_long_splittings, "[[", 1)
place_of_birth$Lon <- sapply(lat_long_splittings, "[[", 2)

## =========================== Tally Locations ==================================
## ==============================================================================
library(plyr)
library(scales)

latlong_location_tally <-
  as.data.frame(table(place_of_birth$Lat.Long))

# latlong_location_tally$Freq <- rescale(latlong_location_tally$Freq, to = c(5,20))

place_of_birth$latlong.location.tally <-
  as.numeric(
    mapvalues(
      place_of_birth$Lat.Long,
      from = latlong_location_tally$Var1,
      to = latlong_location_tally$Freq
    )
  )

county_location_tally <-
  as.data.frame(table(place_of_birth$PoB..County.))

## =========================== Drop Missing Dates ===============================
## ==============================================================================
library(lubridate)

place_of_birth <- place_of_birth[!is.na(place_of_birth$DoB), ]
## Find those entries with (Bapt.) for encoding in a new data column
place_of_birth$Known_Baptism <- grepl("Bapt.", place_of_birth$DoB)
## Function to fix dates with (Bapt.) in
correct_bapt_dates <- function(date) {
  if (grepl("Bapt.", date)) {
    unlist(strsplit(date, "\\s+"))[1]
  } else
    date
}
## Update DoB column
place_of_birth$DoB <-
  unlist(lapply(place_of_birth$DoB, function(x) {
    correct_bapt_dates(x)
  }))

## Use dmy to kill dates which are not properly formatted
place_of_birth$DoB <-
  force_tz(dmy(place_of_birth$DoB), tzone = "GMT")
## Drop those where date is unknown
place_of_birth <- place_of_birth[!is.na(place_of_birth$DoB), ]
```

```{r map}
library(leaflet)
m <- leaflet(place_of_birth) %>%
  addTiles() %>%
  setView(lat = 53.347778, lng = -6.259722, zoom = 6) %>%
  addCircleMarkers(
    lng = ~Lon,
    lat = ~Lat,
    radius = rescale(place_of_birth$latlong.location.tally, to = c(5,20)),
    popup = paste0("Location Name: ",as.character(place_of_birth$PoB..Town.or.Parish.),
                  "<br/>",
                  "Births at location: ",
                  as.character(place_of_birth$latlong.location.tally))
  )
m
```

