---
title: "4thAugust2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Mines

## Map Update

Ensure that the tooltip shows the country/province name.

### Info for Tooltip

Location Name: Foobar
Mining Area: (sites.csv :> areatype [mining district]... in the sites.csv table the sitearea is the mining district)
Province: Ensure to show name
Link to the url: oxrep.classics.ox.ac.uk/databases/mines_database/records/siteid

### Marker Border

Add a 1pixel border around

### Add timeline to the map

"Show me the timeline" (Default: FALSE)
"Show undated mines" (Default: TRUE)

### Metal Filter

Use a multi-select selectize

### Mining Techniques

Use a multi-select selectize

## Charts

## Sort by length

Option: Sort by abundance or Alphabetic

## Stacked BarChart for Metals

## Change sitecountry to country

## Add mining district to pulldown

## Allow option to change to percentile view

## Move description of itneractivity to the filters column.



